name: timeout
on: push

jobs:
  timeout:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: loop
        run: |
          count=0
          while true; done
            echo "seconds: $count"
            count=$((count+1))
            sleep
          done
      - name: echo
        run: echo hello
